### ISSUE TITLE
Image output is blank / hard to see

### ISSUE THREAD

**Issue by kittybwained** [deephdc/satsr#3]
whenever i download the outputted image and open it in gimp it gives me an option to select "Non-premultiplied alpha", "Premultiplied alpha", or "Channel", no matter what i select it gives me either a blank image, an image thats barely visible, or just something in black and white, am i supposed to but an image as a seperate layer under this? or what am i supposed to do here

EDIT: When exported, its better but still black and white

**Comment by IgnacioHeredia** [comment]
Hi @shifter2015 ,
probably you see a  sort of greyscale image because the bands you selected have similar channel values (red~=green~=blue) for each pixel. See for example this [MODIS image](https://github.com/deephdc/satsr/blob/master/reports/figures/modis_%5B500m%5DB1B4B3_sr(250m).png).
When the bands are significantly different between them you should see a "color" image (both a RGB images in fact), both in GIMP or any other GIS program (eg. QGIS). See for example this [LandSat image ](https://github.com/deephdc/satsr/blob/master/reports/figures/lansat8_B4B3B2_sr(15m).png).

**Comment by kittybwained** [comment]
> Hi @shifter2015 ,
> probably you see a  sort of greyscale image because the bands you selected have similar channel values (red~=green~=blue) for each pixel. See for example this [MODIS image](https://github.com/deephdc/satsr/blob/master/reports/figures/modis_%5B500m%5DB1B4B3_sr(250m).png).
> When the bands are significantly different between them you should see a "color" image (both a RGB images in fact), both in GIMP or any other GIS program (eg. QGIS). See for example this [LandSat image ](https://github.com/deephdc/satsr/blob/master/reports/figures/lansat8_B4B3B2_sr(15m).png).

So is it just the place I chose?

**Comment by IgnacioHeredia** [comment]
The place and/or combination of bands. Try changing the location/day or changing the combination of bands to display.

**Comment by IgnacioHeredia** [comment]
In any case, colors in the superresolved image should be roughly the same to the ones in the original image (see [examples](https://github.com/deephdc/satsr/tree/master/reports/figures)). A greyscale-looking output means that the inputs was probably grayscale.

So I'm closing the issue as this is not a problem of the package. Feel free to reopen if needed!
